App/pom.xml
ChatListView/pom.xml
EmojiData/pom.xml
EmojiPopOver/pom.xml
EmojiTextArea/pom.xml
pom.xml
services/orientation/pom.xml
services/position/pom.xml

#12 Rename groupId

---

.travis.yml

This PR builds native images for ChatApp on Linux environment by running `mvn client:build`.

Build using Travis

---

.gitignore
pom.xml

* Add plugin repositories to `pom.xml`
* Add snapshot repository to repositories tag
* Update client-maven-plugin-version to `0.1.17-SNAPSHOT`
* Improvement to `.gitignore` file

Updates to pom and .gitignore

---

App/src/main/java/com/gluonhq/chat/views/MessageCell.java
App/src/main/resources/com/gluonhq/chat/views/chat.css
App/src/main/resources/com/gluonhq/chat/views/chat.fxml

UI changes to the ChatListView.
Before/After image for consideration:

UI changes to ChatListView

---

App/pom.xml
pom.xml

Update plugins and dependencies to latest version

---

App/src/main/java/com/gluonhq/chat/model/Channel.java
App/src/main/java/com/gluonhq/chat/model/ChatMessage.java
App/src/main/java/com/gluonhq/chat/service/CloudlinkService.java
App/src/main/java/com/gluonhq/chat/service/DummyService.java
App/src/main/java/com/gluonhq/chat/service/Service.java
App/src/main/java/com/gluonhq/chat/views/AppViewManager.java
App/src/main/java/com/gluonhq/chat/views/ChannelPresenter.java
App/src/main/java/com/gluonhq/chat/views/ChatPresenter.java
App/src/main/java/com/gluonhq/chat/views/MapsPresenter.java
App/src/main/java/com/gluonhq/chat/views/helper/PlusPopupView.java

Sort channels list by last activity

---

App/src/main/java/com/gluonhq/chat/model/Channel.java
App/src/main/java/com/gluonhq/chat/service/DummyService.java
App/src/main/java/com/gluonhq/chat/views/ChannelCell.java
App/src/main/resources/com/gluonhq/chat/views/channel.css

add styleclass for channels with unread messages

---

App/src/main/java/com/gluonhq/chat/model/ChatMessage.java
App/src/main/java/com/gluonhq/chat/model/User.java
App/src/main/java/com/gluonhq/chat/views/ChatPresenter.java

Sets origin to a message, so that we can handle local messages different.

Prepare for wave integration

---

App/src/main/resources/META-INF/substrate/config/reflectionconfig.json

Fix reflection config file typo and add missing method

---

App/pom.xml
App/src/main/java/com/gluonhq/chat/GluonChat.java
App/src/main/java/com/gluonhq/chat/views/AppViewManager.java
App/src/main/java/com/gluonhq/chat/views/ChannelPresenter.java
App/src/main/java/com/gluonhq/chat/views/ChatPresenter.java
App/src/main/java/com/gluonhq/chat/views/HomePresenter.java
App/src/main/java/com/gluonhq/chat/views/LandscapePresenter.java
App/src/main/java/com/gluonhq/chat/views/LoginPresenter.java
App/src/main/java/com/gluonhq/chat/views/MapsPresenter.java
App/src/main/java/com/gluonhq/chat/views/PortraitPresenter.java
App/src/main/resources/META-INF/substrate/config/reflectionconfig.json
pom.xml

Use Charm 6.1.0

---

.github/scripts/build_app_mac.sh
.github/workflows/macos.yml

Run jpackage for mac from GhA

---

App/src/main/java/com/gluonhq/chat/views/ChannelPresenter.java
App/src/main/resources/com/gluonhq/chat/views/channel.css
App/src/main/resources/com/gluonhq/chat/views/channel.properties

Style floating header

---

App/src/main/java/com/gluonhq/chat/model/User.java
App/src/main/java/com/gluonhq/chat/service/Service.java

Strip bidi protection from user 

---

App/src/main/java/com/gluonhq/chat/service/WaveService.java

fix issue when file didn't yet exist

---

App/src/main/java/com/gluonhq/chat/views/ChannelPresenter.java
App/src/main/java/com/gluonhq/chat/views/HomePresenter.java

Show a placeholder while contacts are being loaded

---

.github/workflows/release.yml
App/pom.xml
App/src/main/java/com/gluonhq/chat/model/GithubRelease.java
App/src/main/java/com/gluonhq/chat/service/Service.java
App/src/main/java/com/gluonhq/chat/service/UpdateService.java
App/src/main/java/com/gluonhq/chat/service/WaveService.java
App/src/main/java/com/gluonhq/chat/views/ChannelPresenter.java
App/src/main/java/module-info.java
App/src/main/resources/about.properties
App/src/main/resources/com/gluonhq/chat/views/channel.css
App/src/main/resources/com/gluonhq/chat/views/channel.fxml

PR queries Github Releases to find if a new release version is present, downloads the binary (windows only) and shows a notification pane for the user to install the latest version.

Auto update: show notification when an update is found

---

App/pom.xml
App/src/main/java/com/gluonhq/chat/service/WaveService.java
App/src/main/java/com/gluonhq/chat/views/MessageCell.java

With this PR, we sent notifications when a message has been read.

117 readnotification

---

App/pom.xml
App/src/main/java/com/gluonhq/chat/model/ChatMessage.java
App/src/main/java/com/gluonhq/chat/service/Service.java
App/src/main/java/com/gluonhq/chat/service/WaveService.java
App/src/main/java/com/gluonhq/chat/views/ChatPresenter.java
App/src/main/java/com/gluonhq/chat/views/MessageCell.java
App/src/main/java/com/gluonhq/chat/views/helper/PlusPopupView.java

172 attachment

---

App/pom.xml
App/src/main/resources/META-INF/substrate/config/reflectionconfig.json
App/src/main/resources/META-INF/substrate/config/resourceconfig-x86_64-darwin.json
App/src/main/resources/META-INF/substrate/config/resourceconfig-x86_64-linux.json

Update reflection lists

---

EmojiData/src/main/java/com/gluonhq/emoji/Emoji.java
EmojiData/src/main/java/com/gluonhq/emoji/EmojiData.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/LinkedEmojiOps.java

Use unicode representation of Emoji

---

App/pom.xml
ChatListView/pom.xml
EmojiData/pom.xml
EmojiData/src/main/java/com/gluonhq/emoji/EmojiData.java
EmojiData/src/main/java/com/gluonhq/emoji/util/TextUtils.java
EmojiData/src/test/java/com/gluonhq/emoji/EmojiDataTest.java
EmojiPopOver/pom.xml
EmojiTextArea/pom.xml
pom.xml
services/orientation/pom.xml
services/position/pom.xml

Fetch emoji from codepoint and unicode string

---

EmojiData/src/main/java/com/gluonhq/emoji/util/TextUtils.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/EmojiTextAreaSkin.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/test/EmojiTextAreaTest.java

Allow pasting emoji unicodes into text area

---

EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/EmojiTextAreaSkin.java

Fix textarea issues

---

EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/EmojiTextAreaSkin.java

Add MacOS related key combinations

---

EmojiTextArea/pom.xml
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/EmojiTextAreaSkin.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/EmptyLinkedEmoji.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/LinkedEmoji.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/LinkedEmojiOps.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/RealLinkedEmoji.java

Use codec to keep emoji unicode and not in realGetText

---

EmojiTextArea/src/main/java/com/gluonhq/emoji/action/Action.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/action/ActionFactory.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/action/BasicAction.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/control/EmojiTextArea.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/EmojiTextAreaSkin.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/StyledTextAreaAction.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/impl/skin/StyledTextAreaActionFactory.java
EmojiTextArea/src/main/java/com/gluonhq/emoji/test/EmojiTextAreaTest.java
EmojiTextArea/src/main/java/module-info.java

Add actions and contextMenu
